### ISSUE TITLE
Unable to use color picker

### ISSUE THREAD

**Issue by mkpazon** [superguigui/simple-color-picker#11]
I am an absolute beginner in node-express. I am trying to use your library. Where do I put the code in Quickstart? In the client-side javascripts? How do I execute `require()` in the client? Thanks.

**Comment by superguigui** [comment]
Hello Mark,

to use `require()` in the client side you need to use a bundler such as Browserify or Webpack.
It can be overwhelming at first but there are a lot of resources and good examples, so hang in there.
You absolutely don't need a node server to use this library, actually it can't work server-side because it uses the dom which is only available in the browser.
In the future we might export a build of the simple-color-picker so that it can be included directly in the html like any other (old school) lib.

Good luck !
